name: color_animating_list_view
description: Creates a ListView that changes background color on Scrolling.
version: 1.0.0
homepage: https://github.com/18-Bytes/color_animating_list_view

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  animate_do: ^4.2.0
  flutter_color: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
